### ISSUE TITLE
Use Environment Variable for modelsPath

### ISSUE THREAD

**Issue by hhxc-0** [amirrezaDev1378/ollama-model-direct-download#2]
Hi,

I noticed that the installer is using a hard-coded `modelsPath`. However, it seems that the path can also be specified using the environment variable `OLLAMA_MODELS` [according to this documentation](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-set-them-to-a-different-location). 

I suggest updating the installer to read the models path from the environment variable. This would allow users to set their preferred download location more easily.

Thanks for considering this!

**Comment by hhxc-0** [comment]
It would be better to first check for the environment variable and use the hard-coded path as a fallback.

**Comment by amirrezaDev1378** [comment]
Hi there,
I can confirm that it currently doesn't use environment variables.
This will be added in the new release.

**Comment by amirrezaDev1378** [comment]
Added support for this. I'm closing this issue.
Please try the new version, and if it does not work as expected, feel free to open another issue.
@hhxc-0
