### ISSUE TITLE
Problem with Installation on Ubuntu 22

### ISSUE THREAD

**Issue by fatemenajafi135** [amirrezaDev1378/ollama-model-direct-download#7]
Thank you for this helpful repository. I tried to install and use the code on my Ubuntu 22 system, but unfortunately, it didn’t work. I’m currently using Ubuntu 22.

**Comment by amirrezaDev1378** [comment]
Can you explain your issue further?
Are you having a specific error?
Also, if you have any logs of the app, please send them.

**Comment by amirrezaDev1378** [comment]
I managed to get the links and install a model on Ubuntu 22.04.

Closing this issue as it does not contain all the information needed.

If you are still having issues with the app, please create a new issue with the proper information.

Also, you can check the new tutorial for this tool [here](https://amirrezadev1378.github.io/ollama-model-direct-download/docs/Installing/).
